version: '3.8'

services:
  backend:
    build: .
    ports:
      - "1234:1234"
    volumes:
      - ./data:/root/data
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data:
